// packages/geospatial-map-angular/src/map-status-chips.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { injectMapRuntime, injectMapStatic } from './map-context'
import { ShapeBadge } from './shapes'
import { optionalBooleanAttribute } from './signals'
import type { MapPlacement } from './types'

/**
 * Non-blocking status chips: loading, no data for the selected time, unavailable at scale.
 * Project `[geoMapLoading]` to replace the "Loading" chip, and `[geoMapEmpty]` for content shown
 * while the map has no layers:
 *
 * ```html
 * <geo-map-status-chips>
 *   <span geoShapeBadge geoMapLoading>Loading indicator statistics…</span>
 *   <p geoMapEmpty>Choose a dataset to start.</p>
 * </geo-map-status-chips>
 * ```
 */
@Component({
  selector: 'geo-map-status-chips',
  imports: [ShapeBadge],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'geo-status-chips',
    'data-slot': 'map-status-chips',
    '[attr.data-placement]': 'placement() ?? map().ui.statusChips.placement',
  },
  template: `
    @let messages = map().messages;
    @if (loading() && (showLoading() ?? map().ui.statusChips.showLoading)) {
      <ng-content select="[geoMapLoading]"
        ><span geoShapeBadge>{{ messages.loading }}</span></ng-content
      >
    }
    @if (noData() && (showNoData() ?? map().ui.statusChips.showNoData)) {
      <span geoShapeBadge>{{ messages.noDataForTime }}</span>
    }
    @if (
      scaleUnavailable() && (showScaleUnavailable() ?? map().ui.statusChips.showScaleUnavailable)
    ) {
      <span geoShapeBadge>{{ messages.unavailableAtScale }}</span>
    }
    @if (!hasLayers()) {
      <ng-content select="[geoMapEmpty]" />
    }
  `,
})
export class MapStatusChips {
  /** Corner of the map; defaults to `ui.statusChips.placement`. */
  readonly placement = input<MapPlacement>()
  /** Shows in-progress layer loads; defaults to `ui.statusChips.showLoading`. */
  readonly showLoading = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  })
  /** Shows layers with no data for the current time; defaults to `ui.statusChips.showNoData`. */
  readonly showNoData = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  })
  /**
   * Shows layers outside their configured zoom range; defaults to
   * `ui.statusChips.showScaleUnavailable`.
   */
  readonly showScaleUnavailable = input<boolean | undefined, unknown>(undefined, {
    transform: optionalBooleanAttribute,
  })

  protected readonly map = injectMapStatic()
  readonly #statuses = injectMapRuntime((map) => map.statuses)
  protected readonly hasLayers = injectMapRuntime((map) => map.layers.length > 0)
  protected readonly loading = computed(() => this.#statuses().some((item) => item.loading))
  protected readonly noData = computed(() => this.#statuses().some((item) => item.noData))
  protected readonly scaleUnavailable = computed(() =>
    this.#statuses().some((item) => item.scaleUnavailable),
  )
}

// packages/geospatial-map/src/map-status-chips.tsx
'use client'

import { forwardRef } from 'react'
import type { ComponentPropsWithoutRef, ReactNode } from 'react'
import { useMapRuntime, useMapStatic } from './map-context'
import { ShapeBadge } from './shapes'
import type { MapPlacement, StatusChipsConfig } from './types'
import { cn } from './utils'

type StatusOptions = Required<
  Pick<StatusChipsConfig, 'showLoading' | 'showNoData' | 'showScaleUnavailable'>
>

export type MapStatusChipsProps = ComponentPropsWithoutRef<'div'> &
  Partial<StatusOptions> & {
    /** Corner of the map; defaults to `ui.statusChips.placement`. */
    placement?: MapPlacement
    /** Replaces the "Loading" chip. */
    loading?: ReactNode
    /** Shown when the map has no layers. */
    empty?: ReactNode
  }

/** Non-blocking status chips: loading, no data for the selected time, unavailable at scale. */
export const MapStatusChips = forwardRef<HTMLDivElement, MapStatusChipsProps>(
  function MapStatusChips(
    {
      placement,
      showLoading,
      showNoData,
      showScaleUnavailable,
      loading: loadingContent,
      empty,
      className,
      ...props
    },
    ref,
  ) {
    const { ui, messages } = useMapStatic()
    const statuses = useMapRuntime((map) => map.statuses)
    const hasLayers = useMapRuntime((map) => map.layers.length > 0)
    const options: StatusOptions = {
      showLoading: showLoading ?? ui.statusChips.showLoading,
      showNoData: showNoData ?? ui.statusChips.showNoData,
      showScaleUnavailable: showScaleUnavailable ?? ui.statusChips.showScaleUnavailable,
    }
    const loading = statuses.some((item) => item.loading)
    const noData = statuses.some((item) => item.noData)
    const scaleUnavailable = statuses.some((item) => item.scaleUnavailable)
    return (
      <div
        ref={ref}
        data-slot="map-status-chips"
        data-placement={placement ?? ui.statusChips.placement}
        {...props}
        className={cn('geo-status-chips', className)}
      >
        {loading &&
          options.showLoading &&
          (loadingContent ?? <ShapeBadge>{messages.loading}</ShapeBadge>)}
        {noData && options.showNoData && <ShapeBadge>{messages.noDataForTime}</ShapeBadge>}
        {scaleUnavailable && options.showScaleUnavailable && (
          <ShapeBadge>{messages.unavailableAtScale}</ShapeBadge>
        )}
        {!hasLayers && empty}
      </div>
    )
  },
)
