// packages/geospatial-map-angular/src/shapes.ts
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  ElementRef,
  Injector,
  afterNextRender,
  booleanAttribute,
  computed,
  inject,
  input,
  linkedSignal,
  model,
  output,
  signal,
} from '@angular/core'
import { injectHostAttribute, partHostStyle } from './signals'
import type { StyleMap } from './signals'
import { sliderFill } from './utils'

// "Shapes" are the small UI primitives every map part is built from. This is the one file to
// edit if you want the map to use your design system: keep the exported names, selectors,
// inputs and outputs, and replace the bodies (for example `hostDirectives: [HlmButton]` from
// spartan/ui, Material's button attributes, or a `<mat-select>` template). Parts use the
// buttons, select, slider and switch in their templates, and apply ShapeCard and ShapeAlert to
// their own host through `hostDirectives`.

/** Lets the part a shape is a host directive of hide it: see `hideWhen`. */
@Directive()
export abstract class PartShape {
  readonly #hidden = signal<() => boolean>(() => false)
  protected readonly shown = computed(() => !this.#hidden()())

  /**
   * Called by a part that applies this shape to its host and has nothing to show (where React
   * renders nothing): the shape drops its class and role while `hidden()` is true.
   */
  hideWhen(hidden: () => boolean): void {
    this.#hidden.set(hidden)
  }
}

/** `<button geoShapeButton>`: a text button. `type` defaults to `button`. */
@Directive({
  selector: 'button[geoShapeButton]',
  host: { class: 'geo-shape-button', 'data-slot': 'button', '[attr.type]': 'type()' },
})
export class ShapeButton {
  readonly type = input<'button' | 'submit' | 'reset'>('button')
}

/** `<button geoShapeIconButton [label]="…">`: an icon button; `label` is its name and tooltip. */
@Directive({
  selector: 'button[geoShapeIconButton]',
  hostDirectives: [{ directive: ShapeButton, inputs: ['type'] }],
  host: {
    class: 'geo-shape-icon-button',
    'data-slot': 'icon-button',
    '[attr.aria-label]': 'consumerLabel ?? label()',
    '[attr.title]': 'label()',
  },
})
export class ShapeIconButton {
  /** Accessible name; also shown as the native tooltip. */
  readonly label = input.required<string>()
  /** A static `aria-label` on the element replaces `label` as the accessible name. */
  protected readonly consumerLabel = injectHostAttribute('aria-label')
}

/** One `<option>` of a ShapeSelect. */
export type ShapeSelectOption = { value: string; label: string; disabled?: boolean }

/**
 * `<geo-shape-select [options]="…" [value]="…" (valueChange)="…">`: a native select without the
 * browser's arrow; the wrapper draws a chevron you can restyle. With `value` it is controlled
 * (it shows `value` again when the change isn't taken); without it, it keeps the user's choice.
 */
@Component({
  selector: 'geo-shape-select',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <span class="geo-shape-select-wrap">
      <select
        #select
        data-slot="select"
        class="geo-shape-select"
        [attr.id]="selectId() ?? null"
        [attr.aria-label]="ariaLabel() ?? null"
        [disabled]="disabled()"
        (change)="changed(select)"
      >
        @for (option of options(); track option.value) {
          <option
            [value]="option.value"
            [disabled]="option.disabled ?? false"
            [selected]="option.value === current()"
            [textContent]="option.label"
          ></option>
        }
      </select>
    </span>
  `,
})
export class ShapeSelect {
  readonly options = input.required<readonly ShapeSelectOption[]>()
  /** The selected value; omit to let the select keep the user's choice. */
  readonly value = input<string>()
  readonly ariaLabel = input<string>()
  /** The select's `id`, for a `<label for>`. */
  readonly selectId = input<string>()
  readonly disabled = input(false, { transform: booleanAttribute })
  readonly valueChange = output<string>()

  protected readonly current = linkedSignal(() => this.value() ?? this.options()[0]?.value ?? '')
  readonly #injector = inject(Injector)

  protected changed(select: HTMLSelectElement): void {
    const next = select.value
    if (this.value() === undefined) this.current.set(next)
    this.valueChange.emit(next)
    // Controlled: show the value the parent has after this change (React's controlled select).
    afterNextRender(
      () => {
        const value = this.value()
        if (value !== undefined && select.value !== value) select.value = value
      },
      { injector: this.#injector },
    )
  }
}

/**
 * `<input type="range" geoShapeSlider [value]="…" (valueChange)="…">`: a range input drawn from
 * the `--geo-slider-*` tokens. Writes the filled share of the track as `--geo-slider-fill`.
 */
@Directive({
  selector: 'input[type=range][geoShapeSlider]',
  host: {
    class: 'geo-shape-slider',
    'data-slot': 'slider',
    '[attr.min]': 'min() ?? null',
    '[attr.max]': 'max() ?? null',
    '[attr.step]': 'step() ?? null',
    '[value]': 'value() ?? ""',
    '[style]': 'hostStyle()',
    '(input)': 'changed()',
  },
})
export class ShapeSlider {
  readonly value = input<number | string>()
  readonly min = input<number | string>()
  readonly max = input<number | string>()
  readonly step = input<number | string>()
  /** The new value while the thumb moves. */
  readonly valueChange = output<number>()

  readonly #element = inject<ElementRef<HTMLInputElement>>(ElementRef).nativeElement
  /** Uncontrolled sliders repaint their fill from what was dragged. */
  readonly #dragged = linkedSignal<number | string | undefined, string | undefined>({
    source: this.value,
    computation: () => undefined,
  })
  protected readonly hostStyle = partHostStyle(
    () => false,
    (): StyleMap => {
      const fill = sliderFill(this.value() ?? this.#dragged(), this.min(), this.max())
      return fill ? { '--geo-slider-fill': fill } : {}
    },
  )

  protected changed(): void {
    if (this.value() === undefined) this.#dragged.set(this.#element.value)
    this.valueChange.emit(Number(this.#element.value))
  }
}

/**
 * `<label geoShapeSwitch [label]="…" [(checked)]="…">`: a checkbox drawn as a switch, with its
 * label. The label element is the host, so a click anywhere on it toggles the switch.
 */
@Component({
  selector: 'label[geoShapeSwitch]',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'geo-shape-switch', 'data-slot': 'switch' },
  template: `
    <input
      type="checkbox"
      class="geo-shape-switch-input"
      [checked]="checked()"
      [disabled]="disabled()"
      (change)="toggle(checkbox)"
      #checkbox
    />
    <span class="geo-shape-switch-track" aria-hidden="true"></span>
    <span class="geo-shape-switch-label">{{ label() }}</span>
  `,
})
export class ShapeSwitch {
  readonly label = input.required<string>()
  readonly checked = model(false)
  readonly disabled = input(false, { transform: booleanAttribute })

  protected toggle(checkbox: HTMLInputElement): void {
    this.checked.set(checkbox.checked)
  }
}

/** `[geoShapeCard]`: a floating surface (panels, legend, popup). */
@Directive({
  selector: '[geoShapeCard]',
  host: { 'data-slot': 'card', '[class.geo-shape-card]': 'shown()' },
})
export class ShapeCard extends PartShape {}

/** `[geoShapeAlert]`: an alert surface with `role="alert"`. */
@Directive({
  selector: '[geoShapeAlert]',
  host: {
    'data-slot': 'alert',
    '[class.geo-shape-alert]': 'shown()',
    '[attr.role]': 'shown() ? "alert" : null',
  },
})
export class ShapeAlert extends PartShape {}

/** `[geoShapeLabel]`: a form label. */
@Directive({
  selector: '[geoShapeLabel]',
  host: { class: 'geo-shape-label', 'data-slot': 'label' },
})
export class ShapeLabel {}

/** `[geoShapeBadge]`: a small status label. */
@Directive({
  selector: '[geoShapeBadge]',
  host: { class: 'geo-shape-badge', 'data-slot': 'badge' },
})
export class ShapeBadge {}

// packages/geospatial-map/src/shapes.tsx
'use client'

import { forwardRef } from 'react'
import type {
  ButtonHTMLAttributes,
  HTMLAttributes,
  InputHTMLAttributes,
  LabelHTMLAttributes,
  ReactNode,
  SelectHTMLAttributes,
} from 'react'
import { cn, sliderFill } from './utils'

// "Shapes" are the small UI primitives every map part is built from. This is the one file to
// edit if you want the map to use your design system: keep the exported names and props, and
// replace the bodies (for example with your shadcn/ui Button, Select, Switch, Slider, Card…).

export type ShapeButtonProps = ButtonHTMLAttributes<HTMLButtonElement>

export const ShapeButton = forwardRef<HTMLButtonElement, ShapeButtonProps>(function ShapeButton(
  { className, type = 'button', ...props },
  ref,
) {
  return (
    <button
      ref={ref}
      type={type}
      data-slot="button"
      className={cn('geo-shape-button', className)}
      {...props}
    />
  )
})

export type ShapeIconButtonProps = ShapeButtonProps & {
  /** Accessible name; also shown as the native tooltip. */
  label: string
  children: ReactNode
}

export const ShapeIconButton = forwardRef<HTMLButtonElement, ShapeIconButtonProps>(
  function ShapeIconButton({ label, className, ...props }, ref) {
    return (
      <ShapeButton
        ref={ref}
        data-slot="icon-button"
        className={cn('geo-shape-icon-button', className)}
        aria-label={label}
        title={label}
        {...props}
      />
    )
  },
)

/** A native select without the browser's arrow; the wrapper draws a chevron you can restyle. */
export const ShapeSelect = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(
  function ShapeSelect({ className, ...props }, ref) {
    return (
      <span className="geo-shape-select-wrap">
        <select
          ref={ref}
          data-slot="select"
          className={cn('geo-shape-select', className)}
          {...props}
        />
      </span>
    )
  },
)

/** A range input drawn from the `--geo-slider-*` tokens. */
export const ShapeSlider = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(
  function ShapeSlider({ className, style, onInput, ...props }, ref) {
    const fill = sliderFill(props.value ?? props.defaultValue, props.min, props.max)
    return (
      <input
        ref={ref}
        type="range"
        data-slot="slider"
        className={cn('geo-shape-slider', className)}
        style={fill ? { ['--geo-slider-fill' as string]: fill, ...style } : style}
        {...props}
        onInput={(event) => {
          // Uncontrolled sliders repaint their fill here; controlled ones re-render.
          if (props.value === undefined) {
            const value = sliderFill(event.currentTarget.value, props.min, props.max)
            if (value) event.currentTarget.style.setProperty('--geo-slider-fill', value)
          }
          onInput?.(event)
        }}
      />
    )
  },
)

export type ShapeSwitchProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> & {
  label: string
}

export const ShapeSwitch = forwardRef<HTMLInputElement, ShapeSwitchProps>(function ShapeSwitch(
  { label, className, ...props },
  ref,
) {
  return (
    <label data-slot="switch" className={cn('geo-shape-switch', className)}>
      <input ref={ref} type="checkbox" className="geo-shape-switch-input" {...props} />
      <span className="geo-shape-switch-track" aria-hidden="true" />
      <span className="geo-shape-switch-label">{label}</span>
    </label>
  )
})

export const ShapeCard = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ShapeCard({ className, ...props }, ref) {
    return <div ref={ref} data-slot="card" className={cn('geo-shape-card', className)} {...props} />
  },
)

export const ShapeAlert = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  function ShapeAlert({ className, ...props }, ref) {
    return (
      <div
        ref={ref}
        role="alert"
        data-slot="alert"
        className={cn('geo-shape-alert', className)}
        {...props}
      />
    )
  },
)

export const ShapeLabel = forwardRef<HTMLLabelElement, LabelHTMLAttributes<HTMLLabelElement>>(
  function ShapeLabel({ className, ...props }, ref) {
    return (
      <label ref={ref} data-slot="label" className={cn('geo-shape-label', className)} {...props} />
    )
  },
)

export const ShapeBadge = forwardRef<HTMLSpanElement, HTMLAttributes<HTMLSpanElement>>(
  function ShapeBadge({ className, ...props }, ref) {
    return (
      <span ref={ref} data-slot="badge" className={cn('geo-shape-badge', className)} {...props} />
    )
  },
)
