// packages/geospatial-map/src/map-tooltip.tsx
'use client'

import { forwardRef, useRef } from 'react'
import type { ComponentPropsWithoutRef, ReactNode } from 'react'
import { sameSelection } from './core/layers/common'
import { useMergedRef } from './hooks'
import { useAnchoredPosition } from './map-anchor'
import { useHoveredFeature, useMapPixel, useMapRuntime, useMapStatic } from './map-context'
import { featureLabel } from './map-state'
import type { FeatureEvent } from './types'
import { cn } from './utils'

export type MapTooltipProps = Omit<ComponentPropsWithoutRef<'div'>, 'children'> & {
  /** Feature properties to try, in order; the first one present is shown. Defaults to `ui.tooltip.fields`. */
  fields?: string[]
  /** Custom content for the hovered feature. Return `null` to show nothing for that feature. */
  children?: ((feature: FeatureEvent) => ReactNode) | undefined
}

/**
 * A small label that follows the pointer over selectable features. By default it shows the
 * feature's `name` (or `title`, or `label`) property. Mouse and pen only: keyboard and screen
 * reader users get the same information from selection and the popup.
 */
export const MapTooltip = forwardRef<HTMLDivElement, MapTooltipProps>(function MapTooltip(
  { fields, className, children, ...props },
  forwardedRef,
) {
  const { ui } = useMapStatic()
  const selection = useMapRuntime((map) => map.state.selection)
  const feature = useHoveredFeature()
  const pixel = useMapPixel(feature?.coordinate)
  const ref = useRef<HTMLDivElement>(null)
  const mergedRef = useMergedRef(ref, forwardedRef)
  useAnchoredPosition(ref, feature ? pixel : undefined, 12)
  // The selected feature already shows its details in the popup.
  if (!feature || sameSelection(selection, feature)) return null
  const content: ReactNode = children
    ? children(feature)
    : featureLabel(feature, fields ?? ui.tooltip.fields)
  if (content === null || content === undefined || content === '') return null
  return (
    <div
      ref={mergedRef}
      data-slot="map-tooltip"
      // The popup and selection announcements carry the same information for assistive
      // technology; announcing every hover would be noise.
      aria-hidden="true"
      {...props}
      className={cn('geo-tooltip', className)}
    >
      {content}
    </div>
  )
})

// packages/geospatial-map-angular/src/map-tooltip.ts
import { NgTemplateOutlet } from '@angular/common'
import { ChangeDetectionStrategy, Component, computed, contentChild, input } from '@angular/core'
import type { TemplateRef } from '@angular/core'
import { sameSelection } from './core/layers/common'
import { anchoredPosition } from './map-anchor'
import {
  injectHoveredFeature,
  injectMapPixel,
  injectMapRuntime,
  injectMapStatic,
} from './map-context'
import { featureLabel } from './map-state'
import { MapTooltipTemplate } from './map-templates'
import { partHostStyle } from './signals'
import type { MapTooltipContext } from './component-types'

/**
 * A small label that follows the pointer over selectable features. By default it shows the
 * feature's `name` (or `title`, or `label`) property; a `<ng-template geoMapTooltip let-feature>`
 * replaces it. Mouse and pen only: keyboard and screen reader users get the same information
 * from selection and the popup. Hidden (with no classes or ARIA) while there is nothing to show.
 */
@Component({
  selector: 'geo-map-tooltip',
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class.geo-tooltip]': '!hidden()',
    '[attr.data-slot]': 'hidden() ? null : "map-tooltip"',
    // The popup and selection announcements carry the same information for assistive
    // technology; announcing every hover would be noise.
    '[attr.aria-hidden]': 'hidden() ? null : "true"',
    '[style]': 'hostStyle()',
  },
  template: `
    @if (context(); as context) {
      @if (contentTemplate(); as content) {
        <ng-container *ngTemplateOutlet="content; context: context" />
      } @else {
        <ng-container>{{ label() }}</ng-container>
      }
    }
  `,
})
export class MapTooltip {
  /** Feature properties to try, in order; the first one present is shown. Defaults to `ui.tooltip.fields`. */
  readonly fields = input<string[]>()
  /** Content for the hovered feature when no `geoMapTooltip` template is inside (`<geo-map>` passes its own). */
  readonly template = input<TemplateRef<MapTooltipContext>>()

  protected readonly map = injectMapStatic()
  readonly #selection = injectMapRuntime((map) => map.state.selection)
  readonly #feature = injectHoveredFeature()
  private readonly ownTemplate = contentChild(MapTooltipTemplate)
  protected readonly contentTemplate = computed(
    () => this.ownTemplate()?.template ?? this.template(),
  )
  protected readonly label = computed(() => {
    const feature = this.#feature()
    return feature
      ? (featureLabel(feature, this.fields() ?? this.map().ui.tooltip.fields) ?? '')
      : ''
  })
  protected readonly context = computed<MapTooltipContext | null>(() => {
    const feature = this.#feature()
    // The selected feature already shows its details in the popup.
    if (!feature || sameSelection(this.#selection(), feature)) return null
    if (!this.contentTemplate() && !this.label()) return null
    return { $implicit: feature, feature }
  })
  protected readonly hidden = computed(() => !this.context())
  protected readonly hostStyle = partHostStyle(() => this.hidden())

  constructor() {
    const pixel = injectMapPixel(() => this.#feature()?.coordinate)
    anchoredPosition(() => (this.context() ? pixel() : undefined), 12)
  }
}
