// apps/demo-angular/src/app/app.ts
import { ChangeDetectionStrategy, Component, computed, signal, viewChild } from '@angular/core'
import {
  GeospatialMap,
  MapControlButton,
  MapControlTemplate,
  MapGrid,
  MapPopupTemplate,
  type ClassificationMethod,
  type MapActions,
  type MapPlacement,
  type MapState,
  type MapStateChangeEvent,
  type MapUiConfig,
  type MapUiProfileId,
  type MapViewState,
  type PaletteId,
} from '@/components/geospatial-map'
import {
  benchmarkNotice,
  classCountOptions,
  classificationOptions,
  createClassifiedIndicator,
  createHarnessCallbacks,
  createHarnessConfig,
  createHarnessGridConfig,
  defaultPlaygroundSettings,
  defaultSymbology,
  defaultUiOverrideJson,
  generatedPolicyJson,
  harnessLayers,
  indicatorTableRows,
  logEvent,
  paletteOptions,
  parseUiOverride,
  placementOptions,
  profileOptions,
  sourceFixtureNotice,
  stableRenderMark,
  worldBounds,
} from '@demo-shared/src/fixtures'
import {
  counterpartDemoHref,
  defaultDemoUrls,
  harnessView,
  isScenarioId,
  parseHarnessParams,
  scenarioOptions,
  type ScenarioId,
} from '@demo-shared/src/scenarios'
import { DemoPopup } from './demo-popup'
import { ArcgisScenario } from './scenarios/arcgis'
import { ChecksScenario } from './scenarios/checks'
import { ComposedScenario } from './scenarios/composed'
import { FeaturesScenario } from './scenarios/features'
import { QuickStartScenario } from './scenarios/quick-start'
import { ThemesScenario } from './scenarios/themes'

// The harness: a port of the React demo's App.tsx, with the same elements, classes, labels and
// test ids, so the shared browser suite runs against both demos. Its scenarios, fixtures,
// configurations and styles come from apps/demo-shared; this file and the scenario components
// only render them.

/**
 * Where the "React version" link points: `REACT_DEMO_URL` when `define` sets it (angular.json,
 * or `ng build --define REACT_DEMO_URL="'https://…'"`), else the React demo's default address.
 */
declare const REACT_DEMO_URL: string | undefined
const reactDemoUrl =
  typeof REACT_DEMO_URL === 'string' && REACT_DEMO_URL ? REACT_DEMO_URL : defaultDemoUrls.react

@Component({
  selector: 'app-root',
  imports: [
    ArcgisScenario,
    ChecksScenario,
    ComposedScenario,
    DemoPopup,
    FeaturesScenario,
    GeospatialMap,
    MapControlButton,
    MapControlTemplate,
    MapGrid,
    MapPopupTemplate,
    QuickStartScenario,
    ThemesScenario,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- ?embed (data-embed): app.css hides the harness chrome and the map fills the window. -->
    <main class="demo-shell" [attr.data-embed]="params.embed ? '' : null">
      <header class="demo-header">
        <div>
          <p class="demo-eyebrow">Component harness</p>
          <h1>Indicator geospatial map</h1>
          <p>
            Vector, raster, projection, time, interaction, legend, grid, and export demonstrations.
          </p>
        </div>
        <div class="demo-header-actions">
          <label class="demo-scenario-control">
            Scenario
            <select #scenarioSelect (change)="chooseScenario(scenarioSelect.value)">
              @for (option of scenarioOptions; track option.id) {
                <option
                  [value]="option.id"
                  [selected]="option.id === scenario()"
                  [textContent]="option.label"
                ></option>
              }
            </select>
          </label>
          <details class="demo-symbology-controls">
            <summary>Style map</summary>
            <fieldset class="demo-symbology-panel">
              <legend>Approved symbology</legend>
              <label>
                Palette
                <select #paletteSelect (change)="choosePalette(paletteSelect.value)">
                  @for (option of paletteOptions; track option.value) {
                    <option
                      [value]="option.value"
                      [selected]="option.value === palette()"
                      [textContent]="option.label"
                    ></option>
                  }
                </select>
              </label>
              <label>
                Classification
                <select #methodSelect (change)="chooseMethod(methodSelect.value)">
                  @for (option of classificationOptions; track option.value) {
                    <option
                      [value]="option.value"
                      [selected]="option.value === method()"
                      [textContent]="option.label"
                    ></option>
                  }
                </select>
              </label>
              <label>
                Classes
                <select #classSelect (change)="chooseClassCount(classSelect.value)">
                  @for (count of classCountOptions; track count) {
                    <option
                      [value]="count"
                      [selected]="count === classCount()"
                      [textContent]="count"
                    ></option>
                  }
                </select>
              </label>
            </fieldset>
          </details>
          <a class="demo-framework-link" [href]="reactHref()">React version</a>
        </div>
      </header>

      @if (params.points > 0) {
        <p class="demo-notice">{{ benchmarkNotice(params.points) }}</p>
      }
      @if (params.sources) {
        <p class="demo-notice">{{ sourceFixtureNotice }}</p>
      }
      @if (params.hidden && !mapVisible()) {
        <button type="button" (click)="mapVisible.set(true)">Reveal map</button>
      }

      @if (scenario() === 'configuration') {
        <section class="demo-configurator" aria-label="Map configuration playground">
          <label>
            Profile
            <select #profileSelect (change)="chooseProfile(profileSelect.value)">
              @for (option of profileOptions; track option.value) {
                <option
                  [value]="option.value"
                  [selected]="option.value === profile()"
                  [textContent]="option.label"
                ></option>
              }
            </select>
          </label>
          <label>
            Control placement
            <select #placementSelect (change)="choosePlacement(placementSelect.value)">
              @for (option of placementOptions; track option.value) {
                <option
                  [value]="option.value"
                  [selected]="option.value === railPlacement()"
                  [textContent]="option.label"
                ></option>
              }
            </select>
          </label>
          <label>
            <input
              #layersBox
              type="checkbox"
              [checked]="showLayers()"
              (change)="showLayers.set(layersBox.checked)"
            />
            Layer panel
          </label>
          <label>
            <input
              #legendBox
              type="checkbox"
              [checked]="showLegend()"
              (change)="showLegend.set(legendBox.checked)"
            />
            Legend
          </label>
          <label>
            <input
              #densityBox
              type="checkbox"
              [checked]="compactTheme()"
              (change)="compactTheme.set(densityBox.checked)"
            />
            Compact density
          </label>
          <label>
            <input
              #translatedBox
              type="checkbox"
              [checked]="translated()"
              (change)="translated.set(translatedBox.checked)"
            />
            Bulgarian labels
          </label>
          <label class="demo-config-json">
            UI override JSON
            <textarea
              #uiJsonField
              [value]="uiJson()"
              (input)="uiJson.set(uiJsonField.value)"
            ></textarea>
          </label>
          <button type="button" (click)="applyUiJson()">Apply JSON</button>
          <output role="status">{{ uiJsonError() || 'Configuration valid' }}</output>
          <details>
            <summary>Generated policy</summary>
            <pre>{{ policyJson() }}</pre>
          </details>
        </section>
      }

      <section [style.display]="mapVisible() ? 'block' : 'none'">
        @switch (view()) {
          @case ('grid') {
            <geo-map-grid
              [config]="gridConfig()"
              (featureSelect)="callbacks.onFeatureSelect($event.event)"
              (viewChange)="callbacks.onViewChange($event.event)"
              (layerStateChange)="callbacks.onLayerStateChange($event.event)"
              (timeChange)="callbacks.onTimeChange($event.event)"
              (metric)="callbacks.onMetric($event.event)"
              (mapError)="callbacks.onError($event.event)"
            >
              <ng-template geoMapPopup let-feature>
                <app-demo-popup [feature]="feature" />
              </ng-template>
              <ng-template geoMapControl="custom:home" let-actions="actions">
                <button geoMapControl label="Fit world" (click)="actions.fit(worldBounds)">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                  >
                    <circle cx="12" cy="12" r="9" />
                    <path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18" />
                  </svg>
                </button>
              </ng-template>
            </geo-map-grid>
          }
          @case ('map') {
            <!-- Keyed like the React map: a new scenario mounts a new map. -->
            @for (key of mapKey(); track key) {
              <geo-map
                [config]="config()"
                [state]="
                  params.controlled ? (controlledState() ?? config().initialState) : undefined
                "
                (stateChangeDetails)="stateChanged($event)"
                (ready)="ready($event)"
                (featureSelect)="callbacks.onFeatureSelect($event)"
                (viewChange)="callbacks.onViewChange($event)"
                (layerStateChange)="callbacks.onLayerStateChange($event)"
                (timeChange)="callbacks.onTimeChange($event)"
                (metric)="callbacks.onMetric($event)"
                (mapError)="callbacks.onError($event)"
              >
                <ng-template geoMapPopup let-feature>
                  <app-demo-popup [feature]="feature" />
                </ng-template>
                <ng-template geoMapControl="custom:home" let-actions="actions">
                  <button geoMapControl label="Fit world" (click)="actions.fit(worldBounds)">
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      aria-hidden="true"
                    >
                      <circle cx="12" cy="12" r="9" />
                      <path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18" />
                    </svg>
                  </button>
                </ng-template>
              </geo-map>
            }
          }
          @case ('quickstart') {
            <app-quick-start />
          }
          @case ('composed') {
            <app-composed [config]="config()" [callbacks]="callbacks" />
          }
          @case ('features') {
            <app-features />
          }
          @case ('arcgis') {
            <app-arcgis />
          }
          @case ('checks') {
            <app-checks />
          }
          @case ('themes') {
            <app-themes />
          }
        }
      </section>

      <details class="demo-data-table">
        <summary>Accessible indicator data table</summary>
        <table>
          <caption>
            Development index values represented by the global map
          </caption>
          <thead>
            <tr>
              <th scope="col">Area</th>
              <th scope="col">Value</th>
              <th scope="col">Category</th>
            </tr>
          </thead>
          <tbody>
            @for (row of indicatorTableRows; track row.key) {
              <tr>
                <th scope="row">{{ row.area }}</th>
                <td>{{ row.value }}</td>
                <td>{{ row.category }}</td>
              </tr>
            }
          </tbody>
        </table>
      </details>

      <section class="demo-inspector" aria-label="Integration inspector">
        <header>
          <div>
            <h2>Integration inspector</h2>
            <p>Typed events and the reusable JSON-safe state contract.</p>
          </div>
          <button type="button" (click)="inspectState()">Inspect state</button>
          <button type="button" (click)="fitSelectedFeature()">Fit selected feature</button>
        </header>
        @if (stateJson()) {
          <pre data-testid="serialized-state">{{ stateJson() }}</pre>
        }
        <ol aria-label="Recent map events">
          @for (event of events(); track $index) {
            <li>{{ event }}</li>
          }
        </ol>
      </section>
    </main>
  `,
})
export class App {
  // The URL never changes while the harness runs: the Scenario select switches in place.
  protected readonly params = parseHarnessParams(location.search)
  protected readonly scenario = signal<ScenarioId>(this.params.scenario)
  protected readonly events = signal<string[]>([])
  protected readonly stateJson = signal('')
  protected readonly mapVisible = signal(!this.params.hidden)
  protected readonly palette = signal<PaletteId>(defaultSymbology.palette)
  protected readonly method = signal<ClassificationMethod>(defaultSymbology.method)
  protected readonly classCount = signal(defaultSymbology.classCount)
  protected readonly profile = signal<MapUiProfileId>(defaultPlaygroundSettings.profile)
  protected readonly railPlacement = signal<MapPlacement>(defaultPlaygroundSettings.railPlacement)
  protected readonly showLegend = signal<boolean>(defaultPlaygroundSettings.showLegend)
  protected readonly showLayers = signal<boolean>(defaultPlaygroundSettings.showLayers)
  protected readonly compactTheme = signal<boolean>(defaultPlaygroundSettings.compactTheme)
  protected readonly translated = signal<boolean>(defaultPlaygroundSettings.translated)
  protected readonly uiJson = signal(defaultUiOverrideJson)
  protected readonly uiOverride = signal<MapUiConfig>(defaultPlaygroundSettings.uiOverride)
  protected readonly uiJsonError = signal('')
  protected readonly controlledState = signal<MapState | null>(null)
  /** The main harness map, while it is on screen. */
  private readonly map = viewChild(GeospatialMap)
  /** The composed scenario's map, while it is on screen. */
  private readonly composed = viewChild(ComposedScenario)

  protected readonly classifiedIndicator = computed(() =>
    createClassifiedIndicator({
      palette: this.palette(),
      method: this.method(),
      classCount: this.classCount(),
    }),
  )
  protected readonly layers = computed(() =>
    harnessLayers(
      this.scenario(),
      {
        sources: this.params.sources,
        points: this.params.points,
        renderer: this.params.renderer,
      },
      this.classifiedIndicator(),
    ),
  )
  protected readonly config = computed(() =>
    createHarnessConfig({
      scenario: this.scenario(),
      layers: this.layers(),
      // The projection is a developer setting (users cannot change it on the map): `?projection=`.
      projection: this.params.projection,
      activeBasemap: this.params.activeBasemap,
      profile: this.profile(),
      railPlacement: this.railPlacement(),
      showLegend: this.showLegend(),
      showLayers: this.showLayers(),
      compactTheme: this.compactTheme(),
      translated: this.translated(),
      uiOverride: this.uiOverride(),
    }),
  )
  protected readonly policyJson = computed(() => generatedPolicyJson(this.config()))
  /** The 3 × 2 grid scenario: the harness config in six regional maps. */
  protected readonly gridConfig = computed(() =>
    createHarnessGridConfig(this.config(), this.classifiedIndicator()),
  )
  /** What the harness renders: a scenario's own component, or the main map. */
  protected readonly view = computed(() => harnessView(this.scenario(), this.params))
  /** The main map's key (React's `key`): one item, so a new key replaces the map. */
  protected readonly mapKey = computed(() => [
    `${this.scenario()}-${this.params.sources}-${this.params.points}`,
  ])
  /** The same route on the React demo, with the scenario on screen. */
  protected readonly reactHref = computed(() =>
    counterpartDemoHref(
      reactDemoUrl,
      location,
      new URL(document.baseURI).pathname,
      this.scenario(),
    ),
  )

  protected readonly callbacks = createHarnessCallbacks((name, detail) => this.record(name, detail))

  protected readonly scenarioOptions = scenarioOptions
  protected readonly paletteOptions = paletteOptions
  protected readonly classificationOptions = classificationOptions
  protected readonly classCountOptions = classCountOptions
  protected readonly profileOptions = profileOptions
  protected readonly placementOptions = placementOptions
  protected readonly indicatorTableRows = indicatorTableRows
  protected readonly sourceFixtureNotice = sourceFixtureNotice
  protected readonly worldBounds = worldBounds
  protected readonly benchmarkNotice = benchmarkNotice

  protected record(name: string, detail: unknown): void {
    this.events.update((current) => logEvent(current, name, detail))
  }

  protected chooseScenario(value: string): void {
    if (isScenarioId(value)) this.scenario.set(value)
  }

  protected choosePalette(value: string): void {
    this.palette.set(value as PaletteId)
    this.record('symbologyControl', { palette: value })
  }

  protected chooseMethod(value: string): void {
    this.method.set(value as ClassificationMethod)
    this.record('symbologyControl', { method: value })
  }

  protected chooseClassCount(value: string): void {
    this.classCount.set(Number(value))
  }

  protected chooseProfile(value: string): void {
    this.profile.set(value as MapUiProfileId)
  }

  protected choosePlacement(value: string): void {
    this.railPlacement.set(value as MapPlacement)
  }

  protected applyUiJson(): void {
    const result = parseUiOverride(this.uiJson())
    if ('ui' in result) {
      this.uiOverride.set(result.ui)
      this.uiJsonError.set('')
    } else {
      this.uiJsonError.set(result.error)
    }
  }

  /** `?controlled`: the host keeps the map's complete state. */
  protected stateChanged({ state, change }: MapStateChangeEvent): void {
    if (!this.params.controlled) return
    this.controlledState.set(state)
    this.record('stateChange', change.domain)
  }

  protected ready(view: MapViewState): void {
    performance.mark(stableRenderMark)
    this.record('ready', view.projection)
  }

  /** The actions of the map on screen (the scenarios with a map of their own add theirs here). */
  protected mapActions(): MapActions | undefined {
    return this.map()?.actions ?? this.composed()?.actions
  }

  protected inspectState(): void {
    this.stateJson.set(JSON.stringify(this.mapActions()?.getState() ?? {}, null, 2))
  }

  protected fitSelectedFeature(): void {
    this.mapActions()?.fitSelection({ maxZoom: 6 })
  }
}

// apps/demo/src/App.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import {
  GeospatialMap,
  MapControlButton,
  MapGrid,
  type ClassificationMethod,
  type FeatureEvent,
  type GeospatialMapHandle,
  type MapPlacement,
  type MapSlots,
  type MapState,
  type MapUiConfig,
  type MapUiProfileId,
  type PaletteId,
} from '@/components/geospatial-map'
import {
  benchmarkNotice,
  classCountOptions,
  classificationOptions,
  createClassifiedIndicator,
  createHarnessCallbacks,
  createHarnessConfig,
  createHarnessGridConfig,
  defaultPlaygroundSettings,
  defaultSymbology,
  defaultUiOverrideJson,
  generatedPolicyJson,
  harnessLayers,
  harnessPopupContent,
  indicatorTableRows,
  logEvent,
  paletteOptions,
  parseUiOverride,
  placementOptions,
  popupLoadingMs,
  profileOptions,
  sourceFixtureNotice,
  stableRenderMark,
  worldBounds,
} from '@demo-shared/src/fixtures'
import {
  counterpartDemoHref,
  defaultDemoUrls,
  harnessView,
  parseHarnessParams,
  scenarioOptions,
  type ScenarioId,
} from '@demo-shared/src/scenarios'
import { ComposedScenario } from './ComposedScenario'
import { ArcgisScenario } from './ArcgisScenario'
import { ChecksScenario } from './ChecksScenario'
import { FeaturesScenario } from './FeaturesScenario'
import { QuickStartScenario } from './QuickStartScenario'
import { ThemesScenario } from './ThemesScenario'
import '@demo-shared/styles/app.css'

// The harness. Its scenarios, fixtures, configurations and styles come from apps/demo-shared,
// which the Angular demo renders too; this file and the *Scenario.tsx files only render them.

const angularDemoUrl = import.meta.env.VITE_ANGULAR_DEMO_URL || defaultDemoUrls.angular

function DemoPopup({ feature }: { feature: FeatureEvent }) {
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    const timer = window.setTimeout(() => setLoading(false), popupLoadingMs)
    return () => window.clearTimeout(timer)
  }, [feature.featureId])
  if (loading) return <p role="status">Loading indicator statistics…</p>
  const { title, statistic, note } = harnessPopupContent(feature)
  return (
    <div className="demo-popup">
      <h2>{title}</h2>
      <p className="demo-statistic">{statistic}</p>
      <p>{note}</p>
    </div>
  )
}

export function App() {
  // The URL never changes while the harness runs: the Scenario select switches in place.
  const [params] = useState(() => parseHarnessParams(window.location.search))
  const {
    sources: sourceMode,
    points: benchmarkCount,
    renderer: benchmarkRenderer,
    controlled: controlledMode,
    hidden: hiddenMode,
    // The projection is a developer setting (users cannot change it on the map): `?projection=`.
    projection: requestedProjection,
    activeBasemap,
  } = params
  const [scenario, setScenario] = useState<ScenarioId>(params.scenario)
  const [events, setEvents] = useState<string[]>([])
  const [stateJson, setStateJson] = useState('')
  const [mapVisible, setMapVisible] = useState(!hiddenMode)
  const [palette, setPalette] = useState<PaletteId>(defaultSymbology.palette)
  const [method, setMethod] = useState<ClassificationMethod>(defaultSymbology.method)
  const [classCount, setClassCount] = useState(defaultSymbology.classCount)
  const [profile, setProfile] = useState<MapUiProfileId>(defaultPlaygroundSettings.profile)
  const [railPlacement, setRailPlacement] = useState<MapPlacement>(
    defaultPlaygroundSettings.railPlacement,
  )
  const [showLegend, setShowLegend] = useState<boolean>(defaultPlaygroundSettings.showLegend)
  const [showLayers, setShowLayers] = useState<boolean>(defaultPlaygroundSettings.showLayers)
  const [compactTheme, setCompactTheme] = useState<boolean>(defaultPlaygroundSettings.compactTheme)
  const [translated, setTranslated] = useState<boolean>(defaultPlaygroundSettings.translated)
  const [uiJson, setUiJson] = useState(defaultUiOverrideJson)
  const [uiOverride, setUiOverride] = useState<MapUiConfig>(defaultPlaygroundSettings.uiOverride)
  const [uiJsonError, setUiJsonError] = useState('')
  const [controlledState, setControlledState] = useState<MapState | null>(null)
  const mapRef = useRef<GeospatialMapHandle>(null)
  const classifiedIndicator = useMemo(
    () => createClassifiedIndicator({ palette, method, classCount }),
    [classCount, method, palette],
  )
  const layers = useMemo(
    () =>
      harnessLayers(
        scenario,
        { sources: sourceMode, points: benchmarkCount, renderer: benchmarkRenderer },
        classifiedIndicator,
      ),
    [benchmarkCount, benchmarkRenderer, classifiedIndicator, scenario, sourceMode],
  )

  const record = (name: string, detail: unknown) =>
    setEvents((current) => logEvent(current, name, detail))
  const config = useMemo(
    () =>
      createHarnessConfig({
        scenario,
        layers,
        projection: requestedProjection,
        activeBasemap,
        profile,
        railPlacement,
        showLegend,
        showLayers,
        compactTheme,
        translated,
        uiOverride,
      }),
    [
      activeBasemap,
      compactTheme,
      layers,
      profile,
      railPlacement,
      requestedProjection,
      scenario,
      showLayers,
      showLegend,
      translated,
      uiOverride,
    ],
  )

  const callbacks = createHarnessCallbacks(record)
  const slots: MapSlots = {
    popup: ({ feature }) => <DemoPopup feature={feature} />,
    controls: {
      'custom:home': ({ actions }) => (
        <MapControlButton label="Fit world" onClick={() => actions.fit(worldBounds)}>
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <circle cx="12" cy="12" r="9" />
            <path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18" />
          </svg>
        </MapControlButton>
      ),
    },
  }
  const content = harnessView(scenario, params)

  // `?embed` (data-embed): app.css hides the harness chrome and the map fills the window.
  return (
    <main className="demo-shell" data-embed={params.embed ? '' : undefined}>
      <header className="demo-header">
        <div>
          <p className="demo-eyebrow">Component harness</p>
          <h1>Indicator geospatial map</h1>
          <p>
            Vector, raster, projection, time, interaction, legend, grid, and export demonstrations.
          </p>
        </div>
        <div className="demo-header-actions">
          <label className="demo-scenario-control">
            Scenario
            <select
              value={scenario}
              onChange={(event) => setScenario(event.currentTarget.value as ScenarioId)}
            >
              {scenarioOptions.map(({ id, label }) => (
                <option key={id} value={id}>
                  {label}
                </option>
              ))}
            </select>
          </label>
          <details className="demo-symbology-controls">
            <summary>Style map</summary>
            <fieldset className="demo-symbology-panel">
              <legend>Approved symbology</legend>
              <label>
                Palette
                <select
                  value={palette}
                  onChange={(event) => {
                    setPalette(event.currentTarget.value as PaletteId)
                    record('symbologyControl', { palette: event.currentTarget.value })
                  }}
                >
                  {paletteOptions.map(({ value, label }) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Classification
                <select
                  value={method}
                  onChange={(event) => {
                    setMethod(event.currentTarget.value as ClassificationMethod)
                    record('symbologyControl', { method: event.currentTarget.value })
                  }}
                >
                  {classificationOptions.map(({ value, label }) => (
                    <option key={value} value={value}>
                      {label}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Classes
                <select
                  value={classCount}
                  onChange={(event) => setClassCount(Number(event.currentTarget.value))}
                >
                  {classCountOptions.map((count) => (
                    <option key={count} value={count}>
                      {count}
                    </option>
                  ))}
                </select>
              </label>
            </fieldset>
          </details>
          <a
            className="demo-framework-link"
            href={counterpartDemoHref(
              angularDemoUrl,
              window.location,
              import.meta.env.BASE_URL,
              scenario,
            )}
          >
            Angular version
          </a>
        </div>
      </header>

      {benchmarkCount > 0 && <p className="demo-notice">{benchmarkNotice(benchmarkCount)}</p>}
      {sourceMode && <p className="demo-notice">{sourceFixtureNotice}</p>}
      {hiddenMode && !mapVisible && <button onClick={() => setMapVisible(true)}>Reveal map</button>}

      {scenario === 'configuration' && (
        <section className="demo-configurator" aria-label="Map configuration playground">
          <label>
            Profile
            <select
              value={profile}
              onChange={(event) => setProfile(event.currentTarget.value as MapUiProfileId)}
            >
              {profileOptions.map(({ value, label }) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </select>
          </label>
          <label>
            Control placement
            <select
              value={railPlacement}
              onChange={(event) => setRailPlacement(event.currentTarget.value as MapPlacement)}
            >
              {placementOptions.map(({ value, label }) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </select>
          </label>
          <label>
            <input
              type="checkbox"
              checked={showLayers}
              onChange={(event) => setShowLayers(event.currentTarget.checked)}
            />{' '}
            Layer panel
          </label>
          <label>
            <input
              type="checkbox"
              checked={showLegend}
              onChange={(event) => setShowLegend(event.currentTarget.checked)}
            />{' '}
            Legend
          </label>
          <label>
            <input
              type="checkbox"
              checked={compactTheme}
              onChange={(event) => setCompactTheme(event.currentTarget.checked)}
            />{' '}
            Compact density
          </label>
          <label>
            <input
              type="checkbox"
              checked={translated}
              onChange={(event) => setTranslated(event.currentTarget.checked)}
            />{' '}
            Bulgarian labels
          </label>
          <label className="demo-config-json">
            UI override JSON
            <textarea value={uiJson} onChange={(event) => setUiJson(event.currentTarget.value)} />
          </label>
          <button
            onClick={() => {
              const result = parseUiOverride(uiJson)
              if ('ui' in result) {
                setUiOverride(result.ui)
                setUiJsonError('')
              } else {
                setUiJsonError(result.error)
              }
            }}
          >
            Apply JSON
          </button>
          <output role="status">{uiJsonError || 'Configuration valid'}</output>
          <details>
            <summary>Generated policy</summary>
            <pre>{generatedPolicyJson(config)}</pre>
          </details>
        </section>
      )}

      <section style={{ display: mapVisible ? 'block' : 'none' }}>
        {content === 'grid' ? (
          <MapGrid
            {...callbacks}
            slots={slots}
            config={createHarnessGridConfig(config, classifiedIndicator)}
          />
        ) : content === 'quickstart' ? (
          <QuickStartScenario />
        ) : content === 'features' ? (
          <FeaturesScenario />
        ) : content === 'themes' ? (
          <ThemesScenario />
        ) : content === 'arcgis' ? (
          <ArcgisScenario />
        ) : content === 'checks' ? (
          <ChecksScenario />
        ) : content === 'composed' ? (
          <ComposedScenario {...callbacks} ref={mapRef} config={config} />
        ) : (
          <GeospatialMap
            {...callbacks}
            key={`${scenario}-${sourceMode}-${benchmarkCount}`}
            ref={mapRef}
            config={config}
            slots={slots}
            {...(controlledMode
              ? {
                  state: controlledState ?? config.initialState,
                  onStateChange: (next: MapState, change: { domain: string }) => {
                    setControlledState(next)
                    record('stateChange', change.domain)
                  },
                }
              : {})}
            onReady={(view) => {
              performance.mark(stableRenderMark)
              record('ready', view.projection)
            }}
          />
        )}
      </section>

      <details className="demo-data-table">
        <summary>Accessible indicator data table</summary>
        <table>
          <caption>Development index values represented by the global map</caption>
          <thead>
            <tr>
              <th scope="col">Area</th>
              <th scope="col">Value</th>
              <th scope="col">Category</th>
            </tr>
          </thead>
          <tbody>
            {indicatorTableRows.map((row) => (
              <tr key={row.key}>
                <th scope="row">{row.area}</th>
                <td>{row.value}</td>
                <td>{row.category}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </details>

      <section className="demo-inspector" aria-label="Integration inspector">
        <header>
          <div>
            <h2>Integration inspector</h2>
            <p>Typed events and the reusable JSON-safe state contract.</p>
          </div>
          <button
            onClick={() => setStateJson(JSON.stringify(mapRef.current?.getState() ?? {}, null, 2))}
          >
            Inspect state
          </button>
          <button onClick={() => mapRef.current?.fitSelection({ maxZoom: 6 })}>
            Fit selected feature
          </button>
        </header>
        {stateJson && <pre data-testid="serialized-state">{stateJson}</pre>}
        <ol aria-label="Recent map events">
          {events.map((event, index) => (
            <li key={`${event}-${index}`}>{event}</li>
          ))}
        </ol>
      </section>
    </main>
  )
}
